# genfont.ps1 - bake a TTF pixel font into source/lazy100/video/font_data.h.
#
# Renders ASCII 32..126 at the font's native pixel size with antialiasing OFF, trims each
# glyph to its ink box (proportional widths), and emits a C header: per-glyph bitmaps +
# per-glyph widths + the cell height. Re-run after swapping the font.
#
#   powershell -ExecutionPolicy Bypass -File tools/genfont.ps1 [ttfPath] [pixelSize]

param(
    [string]$TtfPath  = "assets/fonts/quaver.ttf",
    [int]   $PixelSize = 8,
    [int]   $SpaceAdvance = 4
)

Add-Type -AssemblyName System.Drawing
$ErrorActionPreference = "Stop"

$ttf = (Resolve-Path $TtfPath).Path
$pfc = New-Object System.Drawing.Text.PrivateFontCollection
$pfc.AddFontFile($ttf)
$fam  = $pfc.Families[0]
$font = New-Object System.Drawing.Font($fam, $PixelSize, [System.Drawing.GraphicsUnit]::Pixel)
$fmt  = [System.Drawing.StringFormat]::GenericTypographic

$CW = 16; $CH = 16 # render canvas (generous; glyphs are trimmed to their ink box)

# Pass 1: render each glyph, capture ink box. Vertical origin is shared (baseline-consistent)
# so we keep absolute rows; only the left side is trimmed per glyph for proportional spacing.
$glyphRows = @()  # per-glyph array of 16-bit row masks (column bits, LSB = left)
$glyphMinX = @()
$glyphW    = @()
$globalMinY = 99
$globalMaxY = 0
for ($code = 32; $code -le 126; $code++) {
    $bmp = New-Object System.Drawing.Bitmap $CW, $CH
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit
    $g.Clear([System.Drawing.Color]::Black)
    $g.DrawString([string][char]$code, $font, [System.Drawing.Brushes]::White, 0, 0, $fmt)
    $g.Dispose()

    $rows = @(); $minX = 99; $maxX = -1
    for ($y = 0; $y -lt $CH; $y++) {
        $b = 0
        for ($x = 0; $x -lt $CW; $x++) {
            if ($bmp.GetPixel($x, $y).G -gt 100) {
                $b = $b -bor (1 -shl $x)
                if ($x -lt $minX) { $minX = $x }
                if ($x -gt $maxX) { $maxX = $x }
                if ($y -lt $globalMinY) { $globalMinY = $y }
                if ($y -gt $globalMaxY) { $globalMaxY = $y }
            }
        }
        $rows += $b
    }
    $bmp.Dispose()
    if ($maxX -lt 0) { $minX = 0; $maxX = -1 } # empty (space)
    $glyphRows += ,$rows
    $glyphMinX += $minX
    $glyphW    += ($maxX - $minX + 1)
}
$font.Dispose()
if ($globalMinY -gt $globalMaxY) { $globalMinY = 0 }
$cellH = $globalMaxY - $globalMinY + 1
Write-Output "font=$($fam.Name) ${PixelSize}px  cellHeight=$cellH (ink rows $globalMinY..$globalMaxY)"

# Pass 2: trim top (shift up by globalMinY) + left-trim each glyph, pack cellH bytes.
$bitmaps = @(); $widths = @()
for ($i = 0; $i -lt $glyphRows.Count; $i++) {
    $w = $glyphW[$i]; $mx = $glyphMinX[$i]
    if ($w -lt 0) { $w = 0 }
    $widths += $w
    $bytes = @()
    for ($y = 0; $y -lt $cellH; $y++) {
        $shifted = (($glyphRows[$i][$y + $globalMinY] -shr $mx) -band 0xff)
        $bytes += $shifted
    }
    $bitmaps += ,$bytes
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("// Generated by tools/genfont.ps1 from $TtfPath ($($fam.Name), ${PixelSize}px, no AA).")
[void]$sb.AppendLine("// ASCII 32..126. bit x of a row byte = column x (LSB = leftmost). Proportional widths.")
[void]$sb.AppendLine("// Do not edit by hand; re-run the generator to change the font.")
[void]$sb.AppendLine("#include <cstdint>")
[void]$sb.AppendLine("namespace lazy100 {")
[void]$sb.AppendLine("inline constexpr int kFontHeight = $cellH;")
[void]$sb.AppendLine("inline constexpr int kFontSpace  = $SpaceAdvance; // advance for ' ' and empty glyphs")
[void]$sb.AppendLine("inline constexpr int kFontGap    = 1;             // pixels between glyphs")
[void]$sb.AppendLine("inline constexpr unsigned char kFontWidth[95] = {")
$wline = "    " + (($widths | ForEach-Object { "$_" }) -join ",")
[void]$sb.AppendLine($wline + ",")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("inline constexpr unsigned char kFontBits[95][$cellH] = {")
foreach ($bm in $bitmaps) {
    [void]$sb.AppendLine("    {" + (($bm | ForEach-Object { "0x{0:x2}" -f $_ }) -join ",") + "},")
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("} // namespace lazy100")
Set-Content -Path "source/lazy100/video/font_data.h" -Value $sb.ToString() -Encoding utf8
Write-Output "wrote source/lazy100/video/font_data.h ($cellH rows/glyph)"
